# Generated by Django 5.0.3 on 2024-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('socio', models.BooleanField(default=False)),
                ('cod_oab', models.CharField(blank=True, max_length=30, null=True)),
                ('nacionalidade', models.CharField(max_length=50)),
                ('data_nasimento', models.DateField()),
                ('formacao', models.TextField()),
            ],
        ),
    ]
