# Generated by Django 5.0.3 on 2024-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
