# Generated by Django 5.0.3 on 2024-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0002_membro_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='img_url',
        ),
        migrations.AddField(
            model_name='membro',
            name='img_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
