# Generated by Django 5.0.3 on 2024-03-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sad_app", "0004_tipopublicacao_publicacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicacao",
            name="img_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="link",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="publicacao",
            name="pdf_path",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publicacao",
            name="descricao",
            field=models.TextField(blank=True, null=True),
        ),
    ]
