# Generated by Django 5.0.3 on 2024-03-25 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0005_publicacao_img_path_publicacao_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_nacionalidade', models.CharField(max_length=50)),
                ('nome_pais', models.CharField(max_length=50)),
                ('sigla_pais', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='publicacao',
            old_name='tipo',
            new_name='fk_tipo',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='data_nasimento',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='nacionalidade',
        ),
        migrations.AddField(
            model_name='membro',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.CharField(choices=[('AD', 'Advogado'), ('CO', 'Consultor')], max_length=2),
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=100)),
                ('nivel_formacao', models.CharField(choices=[('GR', 'Graduação'), ('ES', 'Especialização'), ('ME', 'Mestrado'), ('DO', 'Doutorado'), ('PD', 'Pós-Doutorado')], max_length=2)),
                ('nome_curso', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('BA', 'Bacharelado'), ('LI', 'Licenciatura'), ('TE', 'Tecnologia'), ('PG', 'Pós-Graduação')], max_length=2)),
                ('ano_entrada', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('ano_conclusao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2028)])),
                ('titulo_tese', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sad_app.membro')),
            ],
        ),
        migrations.AddField(
            model_name='membro',
            name='fk_maximo_formacao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='sad_app.formacao'),
        ),
        migrations.AddField(
            model_name='membro',
            name='fk_nacionalidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sad_app.nacionalidade'),
            preserve_default=False,
        ),
    ]
