# Generated by Django 5.0.3 on 2024-03-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0006_nacionalidade_rename_tipo_publicacao_fk_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membro',
            name='fk_maximo_formacao',
        ),
    ]
