# Generated by Django 5.0.3 on 2024-03-29 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0007_remove_membro_fk_maximo_formacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacao',
            name='ano_conclusao',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2028)]),
        ),
    ]
