# Generated by Django 5.0.3 on 2024-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0008_alter_formacao_ano_conclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
