# Generated by Django 5.0.3 on 2024-04-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sad_app', '0011_alter_instituicao_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacao',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='nivel_formacao',
        ),
        migrations.RemoveField(
            model_name='formacao',
            name='nome_curso',
        ),
        migrations.AddField(
            model_name='formacao',
            name='fk_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sad_app.curso'),
        ),
        migrations.AlterField(
            model_name='membro',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sad_app.cargo'),
        ),
    ]
